[workspace]
resolver = "3"
members = [ "crates/*" ]

[workspace.package]
version = "0.0.1"
edition = "2024"
rust-version = "1.98"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Mysvac/zlim"

[workspace.lints.rust]
unsafe_code = "deny"
unsafe_op_in_unsafe_fn = "warn"
unused_qualifications = "warn"

[workspace.lints.clippy]
std_instead_of_core = "warn"
alloc_instead_of_core = "warn"

type_complexity = "allow"
too_many_arguments = "allow"

print_stdout = "warn"
print_stderr = "warn"
allow_attributes = "warn"
allow_attributes_without_reason = "warn"

type_id_on_box = "deny"
missing_transmute_annotations = "deny"

[lints]
workspace = true

[package]
name = "zlim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
exclude = [".github", "AGENTS.md", "STYLE_GUIDE.md"]

[dependencies]

zlim-internal = { path = "./crates/zlim-internal", default-features = false }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
zlim-dylib = { path = "./crates/zlim-dylib", default-features = false, optional = true }

[features]

# ----------------------------------------------------------

default = []

# ----------------------------------------------------------
# Basic

# Forces dynamic linking, which improves iterative compile times.
# - Not effective in wasm target.
dylib = ["dep:zlim-dylib", "zlim-internal/dylib"]

# Forces all engine tasks to run on a single thread.
# - Not effective in wasm target that is always single-threaded.
single_thread = ["zlim-internal/single_thread"]

# ----------------------------------------------------------
# default

# Enables default compile time log level and filter out useless logs.
# - log: `max_level_info` + `release_max_level_warn`
# - tracing: `max_level_debug` + `release_max_level_info`
# - zlim_log: as same as `tracing`.
# Eliminate many third-party crates' logs during compilation to optimize performance.
default_log_level = ["zlim-internal/default_log_level"]

# ----------------------------------------------------------
# combination

# COLLECTION: Enables this feature to improve the development experience.
# - This feature provides better debugging information.
# - This feature should not be enabled for published apps!
dev = ["debug", "trace", "backtrace"]

# COLLECTION: Enables editor related dependencies.
# - Enables editor-specific dependencies.
# - Enables developer-friendly error messages and more debug-assertions.
# - Enables dynamic linking for faster rebuild times during development.
# - This feature should not be enabled for published apps!
editor = [
    "dev",
    "dylib",
    "zlim-sysinfo",
]

# ----------------------------------------------------------
# optional sub-crates

# Enables `zlim-sample` crate.
zlim-sample = ["zlim-internal/zlim-sample"]

# Enables `zlim-sysinfo` crate.
# - Not effective in wasm target or other unsupport platforms.
zlim-sysinfo = ["zlim-internal/zlim-sysinfo"]

# ----------------------------------------------------------
# others

# Improves panic backtrace, filter noisy rows.
backtrace = ["zlim-internal/backtrace"]

# Improves debug information, increase debug-assertions.
debug = ["zlim-internal/debug"]

# Tracing support, improves panic information.
trace = ["zlim-internal/trace"]

# Tracing support, exposing a port for Tracy.
# - This feature cannot be used in wasm target.
# - This feature should not be enabled for published apps!
trace_tracy = ["zlim-internal/trace_tracy", "trace"]

# Tracing support, with memory profiling, exposing a port for Tracy.
# - This feature cannot be used in wasm target.
# - This feature should not be enabled for published apps!
trace_memory = ["zlim-internal/trace_memory"]

# Tracing support, saving a file in Chrome Tracing format.
# - This feature cannot be used in wasm target.
# - This feature should not be enabled for published apps!
trace_chrome = ["zlim-internal/trace_chrome", "trace"]

# Use async-io's implementation of block_on in multi-thread mode.
# - This is preferred if your application uses async-io.
# - Not effective in single-thread mode or wasm target.
async-io = ["zlim-internal/async-io"]

# ----------------------------------------------------------

[package.metadata.docs.rs]

no-default-features = true

features = [
    "dev",
    "zlim-sample",
    "zlim-sysinfo",
]
