[package]
name = "zlim-diagnostic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
zlim-utils = { path = "../zlim-utils", default-features = false }
zlim-os = { path = "../zlim-os", default-features = false }
zlim-log = { path = "../zlim-log", default-features = false }

zlim-reflect = { path = "../zlim-reflect", default-features = false }
zlim-core = { path = "../zlim-core", default-features = false }
zlim-app = { path = "../zlim-app", default-features = false }

[lints]
workspace = true
