[package]
name = "zlim-math"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
exclude = ["README.zh.md"]

[features]
libm = ["dep:libm", "glam/libm"]

debug = ["glam/debug-glam-assert"]

approx = ["dep:approx", "glam/approx"]

rand = ["dep:rand", "glam/rand"]

[dependencies]

zlim-log = { path = "../zlim-log", default-features = false }
zlim-utils = { path = "../zlim-utils", default-features = false }
zlim-reflect = { path = "../zlim-reflect", default-features = false, features = ["glam"] }

glam = { version = "0.33", default-features = false, features = ["std", "bytemuck", "serde", "float-types", "integer-types"] }
libm = { version = "0.2", optional = true }
approx = { version = "0.5", default-features = false, optional = true }
rand = { version = "0.10", default-features = false, features = ["std"], optional = true }

serde = { version = "1.0", default-features = false, features = ["std", "derive"] }

[dev-dependencies]
approx = "0.5"
glam = { version = "0.33", default-features = false, features = ["approx"] }
rand = { version = "0.10", default-features = false, features = ["std", "std_rng", "thread_rng"] }
chacha20 = { version = "0.10.0", default-features = false, features = ["rng"] }

[lints]
workspace = true
