[package]
name = "zlim-log"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
exclude = ["README.zh.md"]

[features]

default_log_level = [
    "log/max_level_info",
    "log/release_max_level_warn",
    "tracing/max_level_debug",
    "tracing/release_max_level_info",
]

debug = []

trace_error = ["dep:tracing-error"]
trace_tracy = ["dep:tracing-tracy"]
trace_chrome = ["dep:tracing-chrome"]

tracy_memory = ["trace_tracy", "dep:tracy-client"]
tracy_system = ["tracing-tracy/system-tracing", "tracy-client/system-tracing"]
tracy_sampling = ["tracing-tracy/sampling", "tracy-client/sampling"]
tracy_broadcast = ["tracing-tracy/broadcast", "tracy-client/broadcast"]
tracy_only_localhost = ["tracing-tracy/only-localhost", "tracy-client/only-localhost"]
tracy_context_switch = ["tracing-tracy/context-switch-tracing", "tracy-client/context-switch-tracing"]
tracy_callstack_inlines = ["tracing-tracy/callstack-inlines", "tracy-client/callstack-inlines"]
tracy_demangle = ["tracing-tracy/demangle", "tracy-client/demangle"]

[dependencies]

# Log Adapters
log = { version = "0.4", default-features = false }
tracing-log = { version = "0.2.0" }

# tracing core
tracing = { version = "0.1", default-features = false, features = ["std"] }
tracing-subscriber = { version = "0.3.23", features = ["registry"] }

# feature: trace
tracing-error = { version = "0.2.1", optional = true }

# feature: trace_tracy
# Tracy dependency compatibility table:
# https://github.com/nagisa/rust_tracy_client
tracing-tracy = { version = "0.12", default-features = false, optional = true, features = ["enable", "ondemand"] }

# feature: trace_chrome
tracing-chrome = { version = "0.7.2", optional = true }

# feature: tracy_memory
tracy-client = { version = "0.19", default-features = false, optional = true, features = ["enable", "ondemand"] }

# Platform Adapters:

[target.'cfg(target_family = "wasm")'.dependencies]
tracing-wasm = "0.2.1"

[target.'cfg(target_os = "ios")'.dependencies]
tracing-oslog = "0.3.0"

[target.'cfg(target_os = "android")'.dependencies]
android_log-sys = "0.3.2"

[lints]
workspace = true
