[package]
name = "zlim-core"
exclude = ["tests"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]

debug = ["zlim-utils/debug", "backtrace"]

trace = []

backtrace = []

[dependencies]

zlim-core-derive = { path = "derive", default-features = false }

zlim-cfg = { path = "../zlim-cfg", default-features = false }
zlim-ptr = { path = "../zlim-ptr", default-features = false }
zlim-reg = { path = "../zlim-reg", default-features = false }

zlim-os = { path = "../zlim-os", default-features = false }
zlim-log = { path = "../zlim-log", default-features = false }
zlim-utils = { path = "../zlim-utils", default-features = false }

zlim-task = { path = "../zlim-task", default-features = false }
zlim-reflect = { path = "../zlim-reflect", default-features = false }

indexmap = { version = "2.14", default-features = false }

serde = { version = "1.0", default-features = false, features = ["std", "derive"] }
erased-serde = { version = "0.4", default-features = false, features = ["std"] }

bitflags = { version = "2.13", default-features = false }
fixedbitset = { version = "0.5", default-features = false }

[lints]
workspace = true
