use crate::entity::{EntityId, EntityMapper};
use crate::error::{ZlimError, ZlimResult};

use super::context::EntityReference;
use super::{IntoTemplate, SpecializeTemplate, Template, TemplateContext};

// -----------------------------------------------------------------------------
// EntityTemplate

/// A [`Template`] of an [`EntityId`].
///
/// An entity cannot be created out of thin air, so a component that refers to one is described by
/// *how* to find that entity instead of by the entity itself: either it is already known, or it is
/// one of the named entities of the scene, which is what a `#Name` in a scene expands to.
///
/// Building a template that was left at [`EntityTemplate::None`] is an error.
///
/// # Variants
///
/// - [`Entity`](EntityTemplate::Entity) holds an `EntityId`, which is a direct identifier. It has
///   three cases:
///   1. The `EntityMapper` of the `TemplateContext` has a mapping for it, in which case the
///      actual value is obtained through the mapping.
///   2. The `EntityMapper` has no mapping for it, but the entity exists directly in the world,
///      in which case the original value is kept.
///   3. The `EntityMapper` has no mapping for it and the entity index itself does not exist,
///      in which case it is replaced with [`EntityId::PLACEHOLDER`].
///
/// - [`EntityReference`](EntityTemplate::EntityReference) is a named entity of the scene, resolved
///   to the entity it stands for when the template is built. It is a half compile-time identifier,
///   generated by a `#Name` statement in the `scn!` macro.
///
/// - [`None`](EntityTemplate::None) means absence. It usually carries two meanings: when used for
///   `ResolvedScene::id` or `Parent`, it means the entity has no explicit id, or that there is no
///   parent entity (i.e. it is a root entity), respectively. But when used as a template for an
///   `EntityId` itself, `None` means the mapping failed.
#[derive(Copy, Clone, Default, Debug, PartialEq, Eq)]
pub enum EntityTemplate {
    /// An entity that is already known.
    Entity(EntityId),

    /// A named entity of the scene, resolved to the entity
    /// it stands for when the template is built.
    EntityReference(EntityReference),

    /// No entity at all, which fails to build.
    #[default]
    None,
}

impl From<EntityId> for EntityTemplate {
    #[inline]
    fn from(entity: EntityId) -> Self {
        Self::Entity(entity)
    }
}

impl From<EntityReference> for EntityTemplate {
    #[inline]
    fn from(entity: EntityReference) -> Self {
        Self::EntityReference(entity)
    }
}

// -----------------------------------------------------------------------------

/// Keeps this type out of the blanket `Clone + Unpin` implementations of [`Template`]
/// and [`IntoTemplate`], which is what allows it to implement [`Template`] itself.
///
/// See [`SpecializeTemplate`] for how the condition works.
impl Unpin for EntityTemplate where for<'a> [()]: SpecializeTemplate {}

impl Template for EntityTemplate {
    type Output = EntityId;

    #[cfg_attr(any(debug_assertions, feature = "debug"), track_caller)]
    fn build_template(&self, context: &mut TemplateContext) -> ZlimResult<Self::Output> {
        const MSG: &str = "no entity was specified for this `EntityTemplate`";
        match self {
            Self::Entity(entity) => Ok(context.entity_mapper().get_mapped(*entity)),
            Self::EntityReference(x) => context.resolve_entity(*x),
            Self::None => Err(ZlimError::error(MSG)),
        }
    }

    #[inline]
    fn clone_template(&self) -> Self {
        *self
    }
}

impl SpecializeTemplate for EntityId {}

impl IntoTemplate for EntityId {
    type Template = EntityTemplate;

    #[inline]
    fn into_template(self) -> Self::Template {
        EntityTemplate::Entity(self)
    }
}

// -----------------------------------------------------------------------------
