//! Derive macro for the [`Reflect`] trait.
//!
//! Architecture: attrs → data (parse) → gen_* (codegen).

mod attrs;
mod data;
mod meta;

mod gen_enum;
mod gen_opaque;
mod gen_reflect;
mod gen_register;
mod gen_struct;
mod gen_tuple;
mod gen_typed;
mod gen_typedb;

use attrs::TypeSkips;
use data::ReflectDerive;

use proc_macro2::TokenStream;
use quote::quote;
use syn::DeriveInput;

/// Entry point for `#[derive(Reflect)]`.
///
/// The derive expands reflection only: [`TypePath`] is a supertrait, but it is
/// generated by the separate `#[derive(TypePath)]`, so that a type that only
/// needs a stable name does not pay for reflection and vice versa.
///
/// Each generated trait can be turned off with `#[reflect(Trait = false)]`. The
/// macro then emits no implementation for it, and the user is expected to write
/// their own.
///
/// [`TypePath`]: zlim_reflect::path::TypePath
pub(crate) fn expand_reflect(input: &DeriveInput) -> TokenStream {
    let zlim_reflect = crate::path::zlim_reflect_path();

    let derive = match ReflectDerive::from_input(input, zlim_reflect) {
        Ok(d) => d,
        Err(e) => return e.into_compile_error(),
    };

    if let Err(e) = check_skips(&derive) {
        return e.into_compile_error();
    }

    let skips = &derive.meta().attrs().skips;

    let typed = (!skips.typed).then(|| gen_typed::gen_typed(&derive));
    let reflect = (!skips.reflect).then(|| gen_reflect::gen_reflect(&derive));

    // The kind decides which trait the macro generates here, so only the
    // matching opt-out is meaningful; `check_skips` has already rejected the
    // rest.
    let ops_trait = match &derive {
        ReflectDerive::Struct(r) => (!skips.struct_).then(|| gen_struct::gen_struct(r)),
        ReflectDerive::Tuple(r) => (!skips.tuple).then(|| gen_tuple::gen_tuple(r)),
        ReflectDerive::UnitStruct(r) => Some(gen_opaque::gen_opaque(r)),
        ReflectDerive::Enum(r) => (!skips.enum_).then(|| gen_enum::gen_enum(r)),
        ReflectDerive::Opaque(_) => None,
    };

    // The database and the auto-registration go together: `TypeDatabase` is the
    // trait, `register_reflect!` is how the type is discovered. Opting out of the
    // trait drops both, and then nothing registers the type at startup.
    let registry = (!skips.type_database).then(|| {
        let typedb = gen_typedb::gen_typedb(&derive);
        let register = gen_register::gen_register(&derive);
        quote! {
            #typedb
            #register
        }
    });

    quote! {
        const _: () = {
            #typed
            #reflect
            #ops_trait
            #registry
        };
    }
}

const KIND_TRAITS: &[(&str, fn(&TypeSkips) -> bool, &str)] = &[
    ("Struct", |s| s.struct_, "a named-field struct"),
    ("Tuple", |s| s.tuple, "a tuple struct"),
    ("Enum", |s| s.enum_, "an enum"),
];

/// Rejects opt-outs that cannot apply to this type.
fn check_skips(derive: &ReflectDerive<'_>) -> syn::Result<()> {
    let skips = &derive.meta().attrs().skips;
    let ident = derive.meta().ident();

    // The trait this type's kind generates. A unit struct is opaque by
    // construction, and `#[reflect(Opaque)]` says so outright.
    let kind_trait = match derive {
        ReflectDerive::Struct(_) => "Struct",
        ReflectDerive::Tuple(_) => "Tuple",
        ReflectDerive::Enum(_) => "Enum",
        ReflectDerive::UnitStruct(_) | ReflectDerive::Opaque(_) => "Opaque",
    };

    // 1. An opt-out that names some other kind.
    if let Some((skip, applies_to)) = KIND_TRAITS
        .iter()
        .find(|(name, set, _)| *name != kind_trait && set(skips))
        .map(|(name, _, applies_to)| (*name, *applies_to))
    {
        let msg = format!(
            "`{ident}` cannot use `#[reflect({skip} = false)]`: its reflection kind is \
             `{kind_trait}`, so `{kind_trait}` is the only kind trait the macro generates for \
             it. `#[reflect({skip} = false)]` applies to {applies_to}."
        );
        return Err(syn::Error::new(ident.span(), msg));
    }

    // 2. A kind trait switched off while `Reflect` still asks for it.
    if !skips.reflect
        && let Some((trait_name, _, _)) = KIND_TRAITS
            .iter()
            .find(|(name, set, _)| *name == kind_trait && set(skips))
    {
        let msg = format!(
            "`{ident}` cannot use `#[reflect({trait_name} = false)]` on its own: the generated \
             `Reflect` dispatches its kind methods to `{trait_name}`, so it cannot be compiled \
             without that impl. Turn off `Reflect` as well — \
             `#[reflect(Reflect = false, {trait_name} = false)]` — and write both by hand."
        );
        return Err(syn::Error::new(ident.span(), msg));
    }

    Ok(())
}
