[package]
name = "zlim-shape"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
exclude = ["README.zh.md"]

[dependencies]

zlim-math = { path = "../zlim-math", default-features = false }
zlim-reflect = { path = "../zlim-reflect", default-features = false }

serde = { version = "1.0", default-features = false, features = ["std", "derive"] }

[dev-dependencies]
zlim-math = { path = "../zlim-math", default-features = false, features = ["approx"] }

approx = "0.5"
glam = { version = "0.33", default-features = false, features = ["approx"] }

[lints]
workspace = true
