[package]
name = "zlim-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
exclude = ["README.zh.md"]

[features]

trace = ["zlim-core/trace", "zlim-log/trace", "dep:tracing-error"]

backtrace = ["zlim-core/backtrace"]

[dependencies]

zlim-app-derive = { path = "derive" }

zlim-cfg = { path = "../zlim-cfg", default-features = false }

zlim-os = { path = "../zlim-os", default-features = false }
zlim-log = { path = "../zlim-log", default-features = false }
zlim-utils = { path = "../zlim-utils", default-features = false }

zlim-task = { path = "../zlim-task", default-features = false }
zlim-reflect = { path = "../zlim-reflect", default-features = false }

zlim-core = { path = "../zlim-core", default-features = false }

# plugin: PanicHandler
tracing-error = { version = "0.2.1", optional = true }

# plugin: Shutdown
[target.'cfg(any(all(unix, not(target_os = "horizon")), windows))'.dependencies]
ctrlc = { version = "3.5.2" }

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = { version = "0.2", default-features = false, features = ["std"] }

js-sys = { version = "0.3", default-features = false, features = ["std"] }
web-sys = { version = "0.3", default-features = false, features = ["std", "Window"] }

[lints]
workspace = true
