[package]
name = "zlim-task"
exclude = ["bench", "tests"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]

single_thread = []

async_io = [ "dep:async-io" ]

[dependencies]

zlim-cfg = { path = "../zlim-cfg", default-features = false }

zlim-os = { path = "../zlim-os", default-features = false }
zlim-log = { path = "../zlim-log", default-features = false }
zlim-utils = { path = "../zlim-utils", default-features = false }

atomic-waker = { version = "1.1", default-features = false }
async-task = { version = "4.7", default-features = false, features = ["std"] }
futures-lite = { version = "2.6", default-features = false, features = ["std"] }

[target.'cfg(target_family = "wasm")'.dependencies]
web-task = { version = "1.1" }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
async-io = { version = "2.6", optional = true }
event-listener = { version = "5.4.2", default-features = false, features = ["std"] }

[lints]
workspace = true
