[package]
name = "zlim-reflect-derive"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[features]

reflect_docs = []

[dependencies]

syn = { version = "2.0", features = ["visit", "visit-mut", "full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
zlim-derive-utils = { path = "../../zlim-derive-utils" }

[lints]
workspace = true
